### ISSUE TITLE
Feature Request: Export Warnings & Errors to excel

### ISSUE THREAD

**Issue by Rajdeep97** [CoderAllan/vscode-angulartools#196]
This has been a long wanted feature as you can see here: https://github.com/Microsoft/vscode/issues/30075

In the same thread, they said they have introduced a API which extension can use.

Can you please include it as a feature in your Extension? It will be greatly appreciated.

**Comment by CoderAllan** [comment]
The AngularTools extension has nothing to do with the Problems pane in VSCode, so I assume you have posted your Feature Request to the wrong repository.
