### ISSUE TITLE
Doesnt work in latest VSC

### ISSUE THREAD

**Issue by uabclst** [CoderAllan/vscode-angulartools#438]
I cant get this extension to work in the latest Visual Studio Code. I install it, but doesnt see its symbol (should there be one?) in the left margin, and can't find any other way to access it whatever I try. 
I have the Angular Language Service extension installed. Could that be the problem?

**Comment by CoderAllan** [comment]
You should see it in the Extension list by typing AngularTools in the search box.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/11722431/232530385-a95e239e-23e4-418b-9816-420090ee7c51.png">
Then after installing the extension you should be able to find the AngularTools commands in the Command Pallette:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/11722431/232531437-6acc540e-50fb-49db-a4c9-146fa5f8a6f1.png">

**Comment by uabclst** [comment]
Thanks, my mistake, I see it now.
