### ISSUE TITLE
Feature Request: Include folders

### ISSUE THREAD

**Issue by ratsey** [CoderAllan/vscode-angulartools#439]
I have a monstrous Angular app.  The component hierarchy errors out due to stack size.  There's a way to exclude folders, could we have a way to 'include' folders?  If set, then only those folders are scanned.

**Comment by CoderAllan** [comment]
Thank you for the feedback :thumbsup:
I will look into it.

**Comment by CoderAllan** [comment]
@ratsey in my opinion this IncludeFolder-setting is a setting specific for each project. The only way I think this could be implemented, is by introducing a settings-file for the vscode-AngularTools extension that is located in your project folder.
I'm thinking something like the .vscodeignore and the .gitignore. I could make the extension read a .vscodeangulartools json settings file where you could have the list of include directories. By specifying the included directories setting, then only those directories in your project would be scanned.
Any objections to this idea?

**Comment by ratsey** [comment]
No objections, sounds perfect!

**Comment by CoderAllan** [comment]
@ratsey I have now uploaded a new version 1.11.0 of the AngularTools extension. Please add a .vscodeangulartools file as described in the README.md file and test if it has solved your issue. There may be other if your directory structure is very big, but let me hear if the current solution to the issue has worked.
