### ISSUE TITLE
Possible case issue in exploring folders?

### ISSUE THREAD

**Issue by pfosser** [CoderAllan/vscode-angulartools#441]
Hi, I'm trying the extension on a Linux system and launching the "Show a graph representing the module hierarchy" I got a popup with the following sort of error (exactly as I see it with respect to linebreaks):
```
A system error occured (ENOENT: no such file or directory, scandir '/-
home/paofos/work/gitrepos/proj-name/src/appname')
```
The folder does exist but it is

`home/paofos/work/gitrepos/proj-name/src/appName` (please note the difference in caseness)

Thank you

**Comment by CoderAllan** [comment]
Hi

I think this issue is somehow related to issue #442 
I will be looking into finding a solution for the case-sensitive filename issue.

Thanks for raising the issue to me.

Best regards

**Comment by CoderAllan** [comment]
@pfosser please try installing the new v1.13.0 version of the extension to verify if my bugfix has solved the issue you experienced.
