### ISSUE TITLE
.vscodeangulartools doesn't allow folders with upper case

### ISSUE THREAD

**Issue by MumiaIrrequieta** [CoderAllan/vscode-angulartools#442]
Hi,

I'm trying to test vscode-angulartools in my angular app and found out that what's breaking it is this "toLowerCase()" here: https://github.com/CoderAllan/vscode-angulartools/blob/abd25296d1d441ca0c56aeb7d396100c4b43e6ce/src/filesystemUtils.ts#L67
Can you please fix it, or will you accept a pull request?

Thanks.

**Comment by CoderAllan** [comment]
@MumiaIrrequieta please try installing the new v1.13.0 version of the extension to verify if my bugfix has solved the issue you experienced.
