### ISSUE TITLE
Not working (on NX, remote WSLg) ?

### ISSUE THREAD

**Issue by work933k** [CoderAllan/vscode-angulartools#443]
Hi,
I saw a collegue of mine using your AngularTools-extension on Visual Studio .NET. It looked very interesting and powerfull, but i use VSCode. I installed the extension on my VSCode, without any errors. But unfortunately none of the AngularTools actions do something. I also didn't see any error-messages appear.

The details of my machine:
* VSCode v1.86.1
* AngularTools extension v1.13.0
* AngularTools extension enabled on the Remote-WSL-environment
* Repository a NX-workspace (integrated monorepos)

**Comment by work933k** [comment]
Never mind.. I see stuff happening after i've upgraded VSCode to v1.88.1.
Thanks for providing this extension.

**Comment by CoderAllan** [comment]
> Never mind.. I see stuff happening after i've upgraded VSCode to v1.88.1. Thanks for providing this extension.

Glad you figured it out :-)
