### ISSUE TITLE
[improvement] "Show the project structure"

### ISSUE THREAD

**Issue by work933k** [CoderAllan/vscode-angulartools#445]
Hi, 
I'm experimenting with your extension. A command i just tried was "Show the project structure".
In the AngularTools Output-window i get the output of something like a "dir/ls"-command. Ok, it does work. Good!

But is it expected that the "node_modules"-folder and ".git"-folder is part of the output? As i'm using NX, i also see folders like "tmp" and "coverage". This all ain't wrong, but i'm just having a hard time to understand the intentions of the "Show the project structure"-command.

Maybe it would be good to filter the project-structure using the .gitignore file?

thanks!

**Comment by CoderAllan** [comment]
Hi,

vscode-angulartools already uses a .vscodeangulartools file for excluding or including folders in other commands, so it only makes sense for the project structure command to honor the settings in the settings file too.

Thanks for the feedback!
/Allan

**Comment by CoderAllan** [comment]
Hi,
Finally got around to looking into your suggestion...
The feature is already implemented. I have not looked into the code for a very long time so I had forgotten that the "Show the project directory structure" command already honors the .vscodeangulartools settings file.
You can read about the settings file in the Project Settings section of the documentation: https://github.com/CoderAllan/vscode-angulartools?tab=readme-ov-file#project-settings
