### ISSUE TITLE
config's excludeDirectories are only parsed if a .vscodeangulartools file exists

### ISSUE THREAD

**Issue by FBosito** [CoderAllan/vscode-angulartools#544]
In the readProjectSettings function all the code is just performed if there is a config file existing

if (fsUtils.fileExists(settingsFilename)) { 
....
}
return settings;

**Comment by FBosito** [comment]
Workaround:
Create an empty .vscodeangulartools file

**Comment by CoderAllan** [comment]
This is working as intended. 
The config file .vscodeangulartools should be created by the user if they want to use the features provided by the config file.
