### ISSUE TITLE
Comments prevents correct recognation of Decorations

### ISSUE THREAD

**Issue by FBosito** [CoderAllan/vscode-angulartools#545]
A file with this content:

/* Angular, Ionic and Typescript modules */
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ScrollingModule } from '@angular/cdk/scrolling';

/* 3rd party modules */

/* Project modules */
import { AbsenceRequestBrowsePageRoutingModule } from './absence-request-browse-routing.module';
import { AbsenceRequestBrowsePage } from './absence-request-browse.page';

import { SharedModule } from 'src/app/shared';
import { BrowseHelpersModule } from 'src/app/modules/browse-helpers';
import { AreaHelpersModule } from 'src/app/modules';
import { FormlyBrowseFilterModule } from 'src/app/modules/formly-browse-filter';

/** ##################################################
 * Decorations
 * ##################################################*/
@NgModule({
  imports: [
    CommonModule,
    SharedModule,
    AbsenceRequestBrowsePageRoutingModule,
    ScrollingModule,
    BrowseHelpersModule,
    FormlyBrowseFilterModule,
    AreaHelpersModule,
  ],
  declarations: [AbsenceRequestBrowsePage],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})

/** ##################################################
 * Class
 * ##################################################*/
export class AbsenceRequestBrowsePageModule {}

is not recognized as NgModule because of the comment before the export class ....
Same problem with @Component, ....

Change RegEx from:
/@NgModule\s*\(\s*(\{.+?\})\s*\)\s*export\s+class\s+(\w+)\s+/ims
to:
/@NgModule\s*\(\s*(\{.+?\})\s*\).+export\s+class\s+(\w+)\s+/ims
or so

**Comment by CoderAllan** [comment]
I will look into this...

**Comment by CoderAllan** [comment]
Thanks @FBosito for your help finding the issue. I appreciate it.
